version: '3.3'

services:
  
  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: app42
      MYSQL_PASSWORD: secret_app42
      MYSQL_DATABASE: app42
    volumes:
      - /tmp/mysql:/var/lib/mysql

  stage:
    image: masdp/final_grafana
    ports:
      - 80:8080
    volumes:
      - type: volume
        source: prometheus
        target: /tmp/prometheus.yml
      - type: volume
        source: grafana
        target: /tmp/grafana
    depends_on:
      - db 

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - type: volume
        source: prometheus
        target: /etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    depends_on:
      - prod

  grafana:
    image: grafana/grafana:8.3.2
    user: root
    volumes:
      - type: volume
        source: prometheus
        target: /var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"

volumes:
  prometheus:
  grafana:
