version: '3.3'

services:
  
  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: app42
      MYSQL_PASSWORD: secret_app42
      MYSQL_DATABASE: app42
    volumes:
      - /tmp/mysql:/var/lib/mysql

  stage:
    image: masdp/final_grafana
    ports:
      - 80:8080
    depends_on:
      - db 

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    depends_on:
      - stage

  grafana:
    image: grafana/grafana:latest
    user: root
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
