version: '3.3'

services:
  
  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: app42
      MYSQL_PASSWORD: secret_app42
      MYSQL_DATABASE: app42
    volumes:
      - /tmp/mysql:/var/lib/mysql

  prod:
    image: masdp/final
    ports:
      - 80:8080
    depends_on:
      - db 
